# Generated by Django 3.0.3 on 2020-02-24 19:06

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=500)),
                ('Last_name', models.CharField(max_length=500)),
                ('Father_name', models.CharField(max_length=500)),
                ('Mother_name', models.CharField(max_length=500)),
                ('Date_of_birth', models.DateField()),
                ('Email_id', models.EmailField(max_length=254, unique=True)),
                ('Mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Admission_no', models.IntegerField(unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('Address', models.CharField(max_length=150)),
                ('countries', django_countries.fields.CountryField(max_length=2)),
                ('City', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Courses')),
            ],
        ),
    ]
